version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: elderwise_postgres_prod
    environment:
      - POSTGRES_USER=produser
      - POSTGRES_PASSWORD=prodpassword
      - POSTGRES_DB=elderwise_prod
      - POSTGRES_TIMEZONE=Asia/Jakarta
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always
    networks:
      - elderwise_network

  mailhog:
    image: mailhog/mailhog
    container_name: elderwise_mailhog_prod
    ports:
      - "1026:1025"
      - "8026:8025"
    networks:
      - elderwise_network
    restart: always

  app:
    image: elginbrian/elderwise:latest
    container_name: elderwise_backend_prod
    environment:
      # Database settings
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=produser
      - POSTGRES_PASSWORD=prodpassword
      - POSTGRES_DB=elderwise_prod
      - POSTGRES_TIMEZONE=Asia/Jakarta

      # Application settings
      - ENV=production

      # Storage settings
      - SUPABASE_URL=https://ucayizjdmgxgwweshzag.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjYXlpempkbWd4Z3d3ZXNoemFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjQwMTgsImV4cCI6MjA1OTM0MDAxOH0.pwFn0khq87rxYRim1lQezFMbot34dSp1xq-8h6XFV0o
      - SUPABASE_BUCKETNAME=elderwise-images

      # - EMAIL_PROVIDER=smtp
      # - EMAIL_HOST=mailhog
      # - EMAIL_PORT=1025
      # - EMAIL_SECURE=false
      # - EMAIL_USERNAME=
      # - EMAIL_PASSWORD=

      - EMAIL_PROVIDER=smtp
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=465
      - EMAIL_USERNAME=elginbrian94@gmail.com
      - EMAIL_PASSWORD=kdlklyerxgrcaxwg
      - EMAIL_SECURE=true

      # Common email settings
      - EMAIL_FROM=alerts@elderwise.com
      - EMAIL_FROM_NAME=Elderwise Alert System
      - EMAIL_CONTINUE_ON_ERROR=true
      - EMAIL_MAX_RETRIES=5
      - EMAIL_HEALTH_CHECK_TIMEOUT=3

      # Other settings
      - NETWORK_TEST_ON_STARTUP=true

    ports:
      - "4001:3000"
    depends_on:
      - postgres
      - mailhog
    restart: always
    networks:
      - elderwise_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/v1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./logs:/app/logs

networks:
  elderwise_network:
    driver: bridge

volumes:
  postgres_data_prod:
