version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: elderwise_postgres_prod
    environment:
      - POSTGRES_USER=produser
      - POSTGRES_PASSWORD=prodpassword
      - POSTGRES_DB=elderwise_prod
      - POSTGRES_TIMEZONE=Asia/Jakarta
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always

  app:
    image: elginbrian/elderwise:latest
    container_name: elderwise_backend_prod
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=produser
      - POSTGRES_PASSWORD=prodpassword
      - POSTGRES_DB=elderwise_prod
      - POSTGRES_TIMEZONE=Asia/Jakarta
      - ENV=production
      - SUPABASE_URL=https://ucayizjdmgxgwweshzag.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjYXlpempkbWd4Z3d3ZXNoemFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjQwMTgsImV4cCI6MjA1OTM0MDAxOH0.pwFn0khq87rxYRim1lQezFMbot34dSp1xq-8h6XFV0o
      - SUPABASE_BUCKETNAME=elderwise-images
      - EMAIL_USERNAME=elginbrian94@gmail.com
      - EMAIL_PASSWORD=kdlklyerxgrcaxwg
      - EMAIL_FROM_NAME=Elderwise Alert System
      - EMAIL_PORT=465
    ports:
      - "4001:3000"
    depends_on:
      - postgres
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: "bridge"

volumes:
  postgres_data_prod:
