version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: elderwise_postgres_dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=elderwise_dev
      - POSTGRES_TIMEZONE=Asia/Jakarta
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  app:
    build: .
    container_name: elderwise_backend_dev
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=elderwise_dev
      - POSTGRES_TIMEZONE=Asia/Jakarta
      - ENV=development
    ports:
      - "4000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data_dev:
