version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: elderwise_postgres_dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=elderwise_dev
      - POSTGRES_TIMEZONE=Asia/Jakarta
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: elderwise_backend_dev
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=elderwise_dev
      - POSTGRES_TIMEZONE=Asia/Jakarta
      - ENV=development
      - SUPABASE_URL=https://ucayizjdmgxgwweshzag.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjYXlpempkbWd4Z3d3ZXNoemFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjQwMTgsImV4cCI6MjA1OTM0MDAxOH0.pwFn0khq87rxYRim1lQezFMbot34dSp1xq-8h6XFV0o
      - SUPABASE_BUCKETNAME=elderwise-images
      - EMAIL_USERNAME=elginbrian94@gmail.com
      - EMAIL_PASSWORD=kdlk lyer xgrc axwg
      - EMAIL_FROM_NAME=Elderwise Alert System
    ports:
      - "4000:3000"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data_dev:
